before:
  hooks:
    - go mod download
    - ci/snap-deps.sh
builds:
  - id: kubecom-linux
    main: ./cmd/kubecom
    binary: kubecom
    ldflags:
      - -s -w -X github.com/AnatolyRugalev/kube-commander/cli.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: kubecom-darwin
    main: ./cmd/kubecom
    binary: kubecom
    ldflags:
      - -s -w -X github.com/AnatolyRugalev/kube-commander/cli.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
  - id: kubecom-windows
    main: ./cmd/kubecom
    binary: kubecom
    ldflags:
      - -s -w -X github.com/AnatolyRugalev/kube-commander/cli.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
  - id: kube-commander-linux
    main: ./cmd/kube-commander
    binary: kube-commander
    ldflags:
      - -s -w -X github.com/AnatolyRugalev/kube-commander/cli.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
  - id: release
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - kubecom-linux
      - kubecom-windows
      - kubecom-darwin
  - id: binaries
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: binary
    builds:
      - kubecom-linux
      - kubecom-windows
      - kubecom-darwin
  - id: aur
    name_template: "aur_{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - kubecom-linux
release:
  ids:
    - release
    - binaries
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
publishers:
  - name: aur
    ids:
      - aur
    cmd: ci/aur/publish.sh {{ .Version }}
snapcrafts:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    publish: false
    builds:
      - kube-commander-linux
    summary: Browse your kubernetes clusters in a casual way
    description: |
      kube-commander (kubecom) is terminal UI for easy interaction with Kubernetes
    grade: stable
    confinement: strict
    license: MIT
    base: core20
    plugs:
      kubeconfig:
        interface: personal-files
        read:
          - $HOME/.kube
    apps:
      kube-commander:
        plugs:
          - kubeconfig
      kubectl:
        plugs:
          - kubeconfig
    extra_files:
      - source: kubectl
        destination: kubectl
        mode: 0755
brews:
  - name: kubecom
    folder: Formula
    homepage: "https://github.com/AnatolyRugalev/kube-commander"
    description: "kubecom is terminal UI for easy interaction with Kubernetes"
    url_template: "https://github.com/AnatolyRugalev/kube-commander/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    skip_upload: false
    ids:
      - release
    tap:
      owner: AnatolyRugalev
      name: homebrew-kubecom
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    dependencies:
      - name: kubectl
