before:
  hooks:
    - go mod download
builds:
- main: ./cmd/kube-commander/main.go
  ldflags:
    - -s -w -X main.version={{.Version}}
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
    - linux
    - darwin
    - openbsd
    - windows
  goarch:
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
#snapcrafts:
#  - publish: true
#    summary: Browse your kubernetes clusters in a casual way
#    description: |
#      kube-commander is a TUI utility which provides an easy way to browse and manage any kubernetes cluster accessible
#      by kubectl
#    grade: stable
#    license: MIT
#    base: core