before:
  hooks:
    - go mod download
builds:
- main: ./cmd/kubecom
  ldflags:
    - -s -w -X github.com/AnatolyRugalev/kube-commander/cli.version={{.Version}}
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - openbsd
    - windows
  goarch:
    - amd64
  hooks:
    pre: ci/aur/set-tag.sh {{.Version}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
snapcrafts:
  - publish: false
    summary: Browse your kubernetes clusters in a casual way
    description: |
      kube-commander is a TUI utility which provides an easy way to browse and manage any kubernetes cluster accessible
      by kubectl
    grade: stable
    confinement: classic
    license: MIT
