before:
  hooks:
    - go mod download
    - ci/snap-preinstall.sh {{.Version}}
builds:
- id: kubecom
  main: ./cmd/kubecom
  binary: kubecom
  ldflags:
    - -s -w -X github.com/AnatolyRugalev/kube-commander/cli.version={{.Version}}
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - openbsd
    - windows
  goarch:
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: binary
  builds:
    - kubecom
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
publishers:
  - name: aur
    ids:
      - kubecom
    cmd: ci/aur/publish.sh {{ .Version }}
snapcrafts:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    publish: true
    builds:
    - kubecom
    summary: Browse your kubernetes clusters in a casual way
    description: |
      kubecom is terminal UI for easy interaction with Kubernetes
    grade: stable
    confinement: strict
    license: MIT
    base: core20
    plugs:
      kubeconfig:
        interface: personal-files
        read:
          - $HOME/.kube
    apps:
      kubecom:
        plugs:
          - kubeconfig
    extra_files:
      - source: kubectl
        destination: bin/kubectl
        mode: 0755
