language: go

go:
  - 1.x

addons:
  apt:
    packages:
      - snapd

env:
  - PATH=/snap/bin:$PATH GO111MODULE=on

install:
  - sudo snap install snapcraft --classic

after_success:
  - openssl aes-256-cbc -K $encrypted_6ac5d215f818_key -iv $encrypted_6ac5d215f818_iv -in ci/snap.login.enc -out ci/snap.login -d
  - snapcraft login --with ci/snap.login

if: tag IS present

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
